### ISSUE TITLE
ApacheHttpClient中文乱码问题

### ISSUE THREAD

**Issue by pengliren** [jpush/jiguang-java-client-common#11]
使用ApacheHttpClient进行测试的时候，中文出现乱码，NativeHttpClient不会出现，是否提供设置字符集的配置项？

**Comment by pengliren** [comment]
StringEntity params = new StringEntity(content, CHARSET);
解决中文乱码问题

**Comment by KenChoi1992** [comment]
@pengliren 都是 utf-8 编码

**Comment by pengliren** [comment]
你查一下ApacheHttpClient这个类，我项目使用的时候出现乱码，修改后就没有问题！

**Comment by pengliren** [comment]
@Override
    public ResponseWrapper sendPost(String url, String content) throws APIConnectionException, APIRequestException {
        ResponseWrapper wrapper = new ResponseWrapper();
        CloseableHttpResponse response = null;
        try {
            HttpPost httpPost = new HttpPost(url);
            httpPost.setHeader(HttpHeaders.AUTHORIZATION, _authCode);
            configHttpRequest(httpPost);
            StringEntity params = new StringEntity(content);
            httpPost.setEntity(params);
            response = getHttpClient(url).execute(httpPost, HttpClientContext.create());
            processResponse(response, wrapper);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (response != null) {
                    response.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return wrapper;
    }

**Comment by pengliren** [comment]
StringEntity params = new StringEntity(content);//这段代码这里

**Comment by naivetoby** [comment]
昨天我也出现了乱码，需要改成            StringEntity params = new StringEntity(content, "UTF-8");
